name: Compilation Check

on:
  pull_request:
    branches: [ main, master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc xorg libxext-dev libx11-dev zlib1g-dev libbsd-dev libxrandr-dev x11proto-dev

    - name: Compile project
      run: make

    - name: Test binary exists
      run: |
        if [ ! -f ./cub3D ]; then
          echo "Binary not created after compilation"
          exit 1
        fi

  test-map-errors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc xorg libxext-dev libx11-dev zlib1g-dev libbsd-dev libxrandr-dev x11proto-dev

    - name: Compile project
      run: make

    - name: Ensure logs directory
      run: mkdir -p logs

    - name: Make script executable
      run: chmod +x ./scripts/test_map_errors.sh

    - name: Run map error tests
      run: ./scripts/test_map_errors.sh

    # - name: Upload test results as artifacts
    #   if: always()
    #   uses: actions/upload-artifact@942562b9c7d4b1f2557f1da21f4d3eb4eb4fd01f2ad78b2a6e187d1b193e0a0f
    #   with:
    #     name: map-error-test-logs
    #     path: logs/
    #     retention-days: 7

    # This rule is currently causing issues, so it has been left commented out for now.
    # We will revisit this later to see if we can generate logs directly from the action (which could be useful).
